// Generated by CoffeeScript 1.12.2
(function() {
  var $, requireDir;

  $ = require('./gulp/plugins');

  requireDir = require('require-dir');

  requireDir('gulp');

  $.gulp.task('clean', function(done) {
    $.del('.tmp').then(function() {
      done();
    });
  });

  $.gulp.task('default', ['inject']);

}).call(this);
