// Generated by CoffeeScript 1.12.2
(function() {
  var $;

  $ = require('./plugins');

  $.gulp.task('copy', function() {
    return $.gulp.src('src/index.html').pipe($.gulp.dest('.tmp/serve'));
  });

  $.gulp.task('inject', ['clean'], function() {
    var appScript, bowerScript;
    bowerScript = $.gulp.src($.mainBowerFiles(), {
      read: false
    });
    appScript = $.gulp.src('src/**/*.js', {
      read: false
    });
    return $.gulp.src('src/index.html').pipe($.inject(bowerScript, {
      name: 'bower'
    })).pipe($.inject(appScript, {
      ignorePath: 'src'
    })).pipe($.gulp.dest('.tmp/serve/'));
  });

}).call(this);
