// Generated by CoffeeScript 1.12.2
(function() {
  var $;

  $ = require('gulp-load-plugins')({
    pattern: ['del', 'main-bower-files', 'browser-sync', 'gulp', 'gulp-*', 'run-sequence']
  });

  Object.assign(exports, $);

}).call(this);
