// Generated by CoffeeScript 1.12.2
(function() {
  var $, bs;

  $ = require('./plugins');

  bs = $.browserSync.create();

  $.gulp.task('serve', function() {
    return bs.init({
      server: {
        baseDir: ['.tmp/serve'],
        routes: {
          '/bower_components': 'bower_components',
          '/app': 'src/app'
        }
      }
    });
  });

}).call(this);
