// Generated by CoffeeScript 1.12.6
(function() {
  var $;

  $ = require('./plugins');

  $.gulp.task('less', function() {
    return $.gulp.src(['src/**/*.less', '!src/dev/**/*.less']).pipe($.plumber()).pipe($.sourcemaps.init()).pipe($.concat('all.less')).pipe($.less()).pipe($.autoprefixer()).pipe($.concat('all.css')).pipe($.sourcemaps.write()).pipe($.gulp.dest('src'));
  });

}).call(this);
