// Generated by CoffeeScript 1.12.2
(function() {
  var $;

  $ = require('./plugins');

  $.gulp.task('watch', ['inject'], function() {
    return $.gulp.watch('src/app/**/*.coffee', function() {
      return $.runSequence('coffee', 'reload');
    });
  });

}).call(this);
